export const SEQUELIZE = 'SEQUELIZE';
export const USERS_REPOSITORY = 'USERS_REPOSITORY';
export const ROLES_REPOSITORY = 'ROLES_REPOSITORY';
export const PERMISSIONS_REPOSITORY = 'PERMISSIONS_REPOSITORY';
export const ROLES_PERMISSIONS_REPOSITORY = 'ROLES_PERMISSIONS_REPOSITORY';
export const PRODUCTS_REPOSITORY = 'PRODUCTS_REPOSITORY';
export const MOTORCYCLE_REPOSITORY = 'MOTORCYCLE_REPOSITORY';
export const MOTORCYCLE_BRANDS_REPOSITORY = 'MOTORCYCLE_BRANDS_REPOSITORY';

export const ERROR_INVALID_CREDENTIALS = 'INVALID_CREDENTIALS';
export const ERROR_USER_NOT_FOUND = 'USER_NOT_FOUND';
